#! /bin/sh

UNIX_STYLE_HOME="/opt/SQuirreL"

cd "$UNIX_STYLE_HOME"

# Check to see if the JVM meets the minimum required to run SQuirreL and inform the user if not and skip 
# launch.  versioncheck.jar is a special jar file which has been compiled with javac version 1.2.2, which 
# should be able to be run by that version of higher. The arguments to JavaVersionChecker below specify the 
# minimum acceptable version (first arg) and any other acceptable subsequent versions.  <MAJOR>.<MINOR> should 
# be all that is necessary for the version form. 
java -cp "$UNIX_STYLE_HOME/lib/versioncheck.jar" JavaVersionChecker 1.6 1.7
if [ "$?" = "1" ]; then
  exit 1
fi

# First entry in classpath is the Squirrel application.
TMP_CP="$UNIX_STYLE_HOME/squirrel-sql.jar"

# Then add all library jars to the classpath.
for a in "$UNIX_STYLE_HOME"/lib/*; do
	TMP_CP="$TMP_CP":"$a";
done

TMP_CP=$TMP_CP:$CLASSPATH
UPDATE_CP=$UPDATE_CP:$CLASSPATH


SCRIPT_ARGS="$1 $2 $3 $4 $5 $6 $7 $8 $9"

# Launch SQuirreL application
java -Xmx256m -cp "$TMP_CP" net.sourceforge.squirrel_sql.client.Main --log-config-file "$UNIX_STYLE_HOME"/log4j.properties --squirrel-home "$UNIX_STYLE_HOME" $SCRIPT_ARGS
