#!/bin/sh

TMPFILE=`mktemp --suffix=.txt`

for A
do

 echo "##########################################" >> $TMPFILE
 echo "### $A" >> $TMPFILE
 echo "##########################################" >> $TMPFILE
 echo "" >> $TMPFILE

 mediainfo "$A"  >> $TMPFILE

done
less $TMPFILE
rm -f $TMPFILE
