#!/bin/bash

# prints list of my processes
TMP=`mktemp /tmp/psm-$USER.XXXXXX`
#echo $TMP

ps -eo user,pid,comm,args > $TMP

if [ -z "$1" ]
then
USER=`whoami`
else
USER=$1
fi
grep "^$USER" "$TMP" | cut -d " " -f 2-

rm -f $TMP
#echo $TMP
