#!/bin/sh

if test -d .svn
then
 echo svn "$@"
 exec svn "$@"
elif git log -1 > /dev/null 2>/dev/null
then
 echo git "$@"
 exec git "$@"
elif hg branch > /dev/null 2>/dev/null
then
 echo hg "$@"
 exec hg "$@"
else
 echo Unknown VCS
 exit 1
fi
