#!/bin/sh

if test '!' -f "$1" ; then
 echo zip filename expected
 exit 1
fi

F="$1"
#D=${F%.*}
D="${F}.d"

echo $D

if test -e "$D" ; then
 echo "Target \"$D\" already exists"
 exit 2
fi

exec unzip -d "$D" "$F"
